server:
  port: 9001                    
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations:classpath:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/