server:
  port: 7007
spring:
  application:
    name: service-feign
  cloud:
    config:
      label: master
      profile: dev
      uri: http://127.0.0.1:9001/
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true